# Generated by Django 3.0.3 on 2020-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(auto_created=True, editable=False, max_length=200, unique=True),
        ),
    ]
