# Generated by Django 3.0.3 on 2020-02-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirts'), ('OW', 'Outwear'), ('SW', 'Sports')], max_length=2),
        ),
    ]
